name: Validate DevHub Pull request

on:
  pull_request:
    branches:
      - master
    paths:
      - 'force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate on DevHub
        uses: ./.github/actions/sf-deploy
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          DRY_RUN: true
          TESTS_TO_RUN: StarWarsControllerTest
          TEST_LEVEL: RunSpecifiedTests
      
